useGroupedVersion: true

version_info_list:
  - value: latest version

version_info_list_mobile:
  - value: latest version
  - value: 3.x
    child:
      - 3.0.0_android
  - value: 2.x
    child:
      - 2.0.2_android
      - 2.0.2_ios
      - 2.0.0_android
      - 2.0.0_ios